### ISSUE TITLE
Invalid Level 9 metadata from XML

### ISSUE THREAD

**Issue by quietvoid** [quietvoid/dovi_tool#104]
Apparently writing a level 9 block with only `source_primary_index: 255` is invalid.
There might be the actual primaries expected in the RPU.

When we write an RPU containing a level 9 block with 255 primaries index, the Dolby verifier panics.

**Comment by saindriches** [comment]
I managed to figure out the predefined list of primaries for L9 and L10, and L9 have a longer list. The `SourceColorModel` field in XML is unrelated to RPU data, should always be 255, and `primary_index: 255` means custom color primaries is present in RPU.
