### ISSUE TITLE
Error: Invalid profile for mode 2 conversion!

### ISSUE THREAD

**Issue by jlw4049** [quietvoid/dovi_tool#112]
Input media info format: Dolby Vision, Version 1.0, dvhe.08.06, BL+RPU, HDR10 compatible / SMPTE ST 2086, HDR10 compatible

If I just choose -m 2 every time, which for combability purposes, I'd want every time, I will get this error if the input is already profile 8: Error: Invalid profile for mode 2 conversion!

Is there anyway to bypass this without having to check the profile before hand?

**Comment by quietvoid** [comment]
Sure, sounds reasonable.

**Comment by jlw4049** [comment]
I appreciate it! I made a wrapper for your cli program, which basically sends mode 2 to every input, as the RPU I want out of it, to encode to x265 with and for maximum combability, errors out if the input is already mode 2. 

Side note, not really related. How are you able to detect which hdr format a hevc file upon input? Mediainfo/ffprobe will not show the proper hdr format of a dolby vision input in hevc format. Only once it's wrapped into a container.

**Comment by quietvoid** [comment]
Mode 2 now overrides back to mode 0 when used on a profile 8 RPU.

> Side note, not really related. How are you able to detect which hdr format a hevc file upon input? Mediainfo/ffprobe will not show the proper hdr format of a dolby vision input in hevc format. Only once it's wrapped into a container.

In ffmpeg 5.0, ffprobe can detect the RPUs for every frame.

**Comment by jlw4049** [comment]
I appreciate the quick work! Thank you for the information on ffprobe.
