### ISSUE TITLE
--crop parameter

### ISSUE THREAD

**Issue by hyllm** [quietvoid/dovi_tool#12]
Has the --crop parameter another variables?? When to use it??? only add --crop when the rpu metadata will be used with cropped encode??? and what about resized encode???

**Comment by quietvoid** [comment]
`--crop` is for fully cropped final video. It's only a flag.

Resized encodes are fine as long as they're cropped as well, otherwise the offsets have to be adjusted.
There is no way to make them custom currently.

**Comment by LukasLohmar** [comment]
> `--crop` is for fully cropped final video. It's only a flag.
> 
> Resized encodes are fine as long as they're cropped as well, otherwise the offsets have to be adjusted. There is no way to make them custom currently.

hello, i was wondering if custom crop params will come eventually. for example when encoding with SVT-HEVC there are only heights with mod8 possible. so often it wont match height when using --crop since it wont hit mod8 all the time.

**Comment by quietvoid** [comment]
You can extract the RPU and edit it in those cases.
It's always better to do that, anyways. `--crop` is just a convenience flag for simple cases.
