### ISSUE TITLE
Crop Clarification

### ISSUE THREAD

**Issue by Ryushin** [quietvoid/dovi_tool#120]
I'm getting mixed messages if I need to use cropping or not.  This is coming from this [thread](https://forum.doom9.org/showthread.php?p=1962458#post1962458)

Essentially I re-encoded all my UHD disc sources into a HDR10 MKV files with the letterbox cropped out (top and bottom for widescreen and sides for 4:3 sources like Snyder's Justice League).  I now want to re-rip all my DV UHD discs using MakeMKV into a MKV file and then extract the DV RPU.bin file and inject it into my cropped encodings.

Since I'm seeing conflicting information, do I use cropping option in the dovi_tool from the source that does have letterbox, to inject into my encoding that has been cropped to remove the letterbox.  Thanks much for creating this tool.

**Comment by quietvoid** [comment]
My suggested workflow is as follows:
- Extract RPU from source with mode 0, to validate the parsing is correct.
- Edit the RPU according to the output/final video needs, using the `editor` subcommand.
- Use the RPU with x265, or if that's not possible (i.e encoding with FFmpeg directly) then using the injector for the final video.

For cropping, I did post a pretty clear explanation before here: https://forum.doom9.org/showpost.php?p=1951422&postcount=33

Source video 2160p with letterbox bars:
>encoded as 2160p with letterbox bars: don't use crop.
encoded as 2160p and cropped (no more letterbox bars): use crop.
encoded as 1080p with letterbox bars: you need to edit the active area to set the final letterbox bars size as offsets, see documentation.
encoded as 1080p and cropped: use crop.

**Comment by Ryushin** [comment]
Thank you.  So the crop command pretty much works the way one logically would expect it to.  If I'm encoding a source and I'm cropping it, extract the DV source with the crop command and then inject it into the cropped encoded video.
