### ISSUE TITLE
Invalid RPU possible bug and exit status is zero on error

### ISSUE THREAD

**Issue by sammys** [quietvoid/dovi_tool#122]
Hi and thanks for creating dovi_tool!

I've encountered an FEL+RPU stream that dovi_tool fails to convert for some reason and upon exit it also has an exit status of zero instead of non-zero. Here is a screenshot of the output.

![Screen Shot 2022-02-04 at 10 44 39](https://user-images.githubusercontent.com/1011469/152468459-4ebbfe93-0660-40fc-a026-cb9c60ce67e6.png)

The bitstream file is 10GB so please advise me how you'd like to receive it.

**Comment by quietvoid** [comment]
I should be able to reproduce this locally without a sample file.
Currently, the return code is always zero. I'll have to look into fixing that.

**Comment by quietvoid** [comment]
Though if you're able to mention the title of the movie, that would work as well.

A sample would be better to see if there's an issue witb the HEVC parser.

**Comment by sammys** [comment]
Happy to give you the details.

Movie: `Crank.Extended.Cut.2006.MULTI.COMPLETE.UHD.BLURAY-GENTLEMAN`

Stream was taken directly from BDMV/STREAM/00002.m2ts using the following command:

`ffmpeg -analyzeduration 2000M -probesize 2000M -hide_banner -i "BDMV/STREAM/00002.m2ts" -c copy -an -sn -map 0:v:1 -vbsf hevc_mp4toannexb -y "example.FEL+RPU.7.hevc"`

In case you are wondering, I also tried piping the FFmpeg output to dovi_tool with the same result.

If you'd like me to post a sample, would it be fastest if you posted a patch I can apply to dovi_tool to make it output the location of the error it finds (if there's no other way to get it to do that)?

**Comment by quietvoid** [comment]
Thanks for the info.
I'll look into it.

**Comment by quietvoid** [comment]
Seems the file is "corrected" by remuxing/demuxing with MKVToolNix. So, currently I'm blaming FFmpeg.

**Comment by quietvoid** [comment]
The parsing should be fixed, and `dovi_tool` should now return a relevant exit code if there's an error.

**Comment by sammys** [comment]
Always those pesky edge cases hehe. Built 1.4.6 and...

![Screen Shot 2022-02-05 at 09 09 01](https://user-images.githubusercontent.com/1011469/152624869-3a94d6b9-46fd-4efb-b2ed-0ee3be97440a.png)

Can't test the exit status as I don't have any invalid streams on hand. Thanks for the quick turnaround!
