### ISSUE TITLE
Validate keyframe alignment of transcoded BL with EL

### ISSUE THREAD

**Issue by sammys** [quietvoid/dovi_tool#125]
As I understand it, profile 7 has a keyframe alignment requirement between BL and EL. Assuming that's correct, would it be possible to add a command to dovi_tool that reads in BL and EL bitstreams and validates keyframe alignment? This would be useful for cases in which the BL is transcoded for some reason.

**Comment by quietvoid** [comment]
Also, given there are many possible ways to get frame types/numbers, I don't think this is something worth doing here.
You can use ffmpeg to obtain the info.

**Comment by ValZapod** [comment]
Allignment for dual layer is specified in Blu-ray spec. Who knows where the very last version of the spec is.

Anyway, who cares, there is no opensource m2ts H.222 conformant muxer.

FFmpeg tried but utterly failed. "Interlaced style" of multiple video streams is too complex, buffer managment is impossible to do. Etc.
