### ISSUE TITLE
what's this mean (extract with -m3 p5 to p8)

### ISSUE THREAD

**Issue by ted423** [quietvoid/dovi_tool#130]
```
dovi_tool  -m 3 extract-rpu _Rip/Coda.2021.2160p.ATVP.hevc 
Error: Condition failed: `self.max_display_mastering_luminance <= MAX_PQ_LUMINANCE` (38528 vs 10000)
```
the hevc is in a mp4 demux with tsmuxer [Nightly build from 2022-03-28-02-41-38]
```
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
Codec ID                                 : dvhe
Codec ID/Info                            : High Efficiency Video Coding with Dolby Vision```

**Comment by ted423** [comment]
found this no is what happens when I try to convert an appletv + web-dl.
in sum to explain myself better ... the first step.
Code: [Select all](https://forum.makemkv.com/forum/viewtopic.php?f=12&t=18602&start=6030#)

dovi_tool -m 3 convert --discard dolby.hevc

**Comment by ted423** [comment]
both appletv + web-dl

**Comment by ted423** [comment]
https://github.com/quietvoid/dovi_tool/issues/49

**Comment by quietvoid** [comment]
The HDR10 fallback metadata (or L6) is invalid.
Extract without specifying a mode and edit the RPU with the editor to lower the values to max 10 000:

```json5
{
    "level6": {
        "max_display_mastering_luminance": 10000,
        "min_display_mastering_luminance": int,
        "max_content_light_level": int,
        "max_frame_average_light_level": int
    },
}
```

Fill in the rest of the L6 with the original metadata.

**Comment by ted423** [comment]
Thanks a lot
