### ISSUE TITLE
Part of '"num_x_partitions_minus1": 2046' should be parsed as nlq_pred_pivot_value

### ISSUE THREAD

**Issue by ValZapod** [quietvoid/dovi_tool#131]
From metafier:
```
  |  nlq_method_idc                            0
  |  nlq_num_pivots                            2
  |  nlq_pred_pivot_value                        0 1023
  |  partitions                                y: 1  x: 1

```

While you parse it as 

    "nlq_method_idc": 0,
    "nlq_num_pivots_minus2": 0,
    "num_x_partitions_minus1": 2046,
    "num_y_partitions_minus1": 0

**Comment by ValZapod** [comment]
See https://github.com/tegzwn/HiSTBLinuxV100R005C00SPC050/blob/356be08d707a80e7b30b30e79b0d528922674b8e/source/msp/api/vo/dolby/include/rpu_api_common.h#L699

**Comment by quietvoid** [comment]
I don't know what you're trying to say.
`num_{x,y}_partitions_minus1` are unrelated to `pred_pivot_value`.

**Comment by ValZapod** [comment]
> `num_{x,y}_partitions_minus1` are unrelated to `pred_pivot_value`.

A little bigger output in metafier (looks like pred_pivot_values is not the same as nlq_pred_pivot_value):
```
  |  pred_pivot_values[ 0 ]                      0 1023
  |  pred_pivot_values[ 1 ]                      0 1023
  |  pred_pivot_values[ 2 ]                      0 1023
  |  nlq_method_idc                            0
  |  nlq_num_pivots                            2
  |  nlq_pred_pivot_value                        0 1023
  |  partitions                                y: 1  x: 1

```

**Comment by quietvoid** [comment]
I don't know what `nlq_pred_pivot_value` is derived from nor what it means.
Partition values are parsed fine, there's no documentation to interpret what they mean.

**Comment by ValZapod** [comment]
From dolby code `uint8_t  num_x_partitions`, so it cannot be 2046. Only 2^8, unsigned.

**Comment by quietvoid** [comment]
It's an unsigned golomb code in the bitstream, where it is parsed. It can definitely be 2046.
Dolby is converting it into the final useable value.

**Comment by saindriches** [comment]
Some info in patent US10587897B2 shows `num_{x,y}_partitions_minus1` will be 0 in all current RPU profile (since no `vdr_rpu_profile == 2` in any known profile, so there is no local partition), can be also confirmed in US10701399B2 (`rpu_data_{mapping, nlq}` is all about x = 0 and y = 0). It shows `nlq_pred_pivot_value` is decoded after `nlq_method_idc`. So at least we can fix this, done after researching with some MEL and FEL sample, seems no problem.
