### ISSUE TITLE
DDVT INJECTOR Error/Crash:  "invalid pps index"

### ISSUE THREAD

**Issue by Rumourd** [quietvoid/dovi_tool#135]
There seems to be a resyncing going on with an encoded 4K-DV file of my **It's A Wonderful Life** mkv file.
DDVT INJECTOR appears to successfully do the resyncing workaround, then moves on to building the HEVC file, but at the end, it crashes out to the error message mentioned in the header.

**Comment by quietvoid** [comment]
Need a sample that reproduces the issue.

**Comment by quietvoid** [comment]
No sample, closing.
