### ISSUE TITLE
Trojan:Script/Oneeva.A!ml

### ISSUE THREAD

**Issue by alexantr** [quietvoid/dovi_tool#136]
I tried to download latest release dovi_tool-1.4.7-x86_64-pc-windows-msvc.zip and MS Defender deleted it. Defender says it found Trojan:Script/Oneeva.A!ml.

Previous release 1.4.6 is OK.

**Comment by FrostByteLXV** [comment]
My Defender deleted it also.
Severe
Detected: Trojan:Script/Wacatac.B!ml
Details: This program is dangerous and executes commands from an attacker.

**Comment by quietvoid** [comment]
Huh, that's weird.

**Comment by quietvoid** [comment]
On my Windows 10 machine, Defender says it's clean FWIW.
Ran it through VirusTotal and there's only one detection.

**Comment by quietvoid** [comment]
There's nothing I can do about this so I'll close.
I had another Windows Defender definitions update and it still comes up clean.

**Comment by da-anda** [comment]
just downloaded the latest version (1.5.4) and defender also deleted it. Oddly 1.5.1 worked fine with no complaints.

**Comment by FrostByteLXV** [comment]
yes, here too.  :(

**Comment by alexantr** [comment]
Versions 1.5.1-1.5.3 are clean. Version 1.5.4 triggers Defender again.
@quietvoid are you using same machine for all release builds?

**Comment by quietvoid** [comment]
The binaries are built by GitHub.

**Comment by alexantr** [comment]
I found many projects on GitHub have same issues and no explicit solution. We can just wait for the new release.

**Comment by saindriches** [comment]
It's a false positive from Defender, just like many other projects, and we can’t expect the result of future releases. Perhaps you should add it to the whitelist.
