### ISSUE TITLE
Request to generate Dolby Profile 8.4 like Dolby Profile 8.1

### ISSUE THREAD

**Issue by 98mxr** [quietvoid/dovi_tool#144]
It seems, level 6 is unnecessary

**Comment by quietvoid** [comment]
Maybe one day, but I have no way to test.

**Comment by 98mxr** [comment]
I've been trying to make Dolby Vision 8.4 on Windows. The way I figured out is to make two "similar" PQ and HLG videos, use madMeasureHDR and dovi_tool to make Dolby 8.1, and then inject the 8.1 file to HLG.hevc. I know this sounds crazy and doesn't make sense, but I also don't have a better way. Is there a way to regenerate RPU.bin from the exported RPU_export.json file, so that I can manually delete level6 to test.

My native language is not English, all of the above are google translated. Sorry for any offense.

**Comment by quietvoid** [comment]
> Is there a way to regenerate RPU.bin from the exported RPU_export.json file, so that I can manually delete level6 to test.

No.

Profile 8.1 is incompatible with HLG base layer, we need to generate an RPU with defaults like iPhone recordings.

**Comment by 98mxr** [comment]
It seems that I know too little about Dolby Profile, thank you for your reply, looking forward to a way to implement this function one day.
