### ISSUE TITLE
variable aspect ratio (with crop)

### ISSUE THREAD

**Issue by mylesmacrae** [quietvoid/dovi_tool#151]
Hi,  I'm trying to preserve DV on a video that switches between 1.9:1 (70/70 top and bottom bars) and 2.39:1 (278/278 top and bottom bars).    The video has been transcoded to crop to the widest frame, so the next challenge is preparing the RPU data accurately.

Would `-c` take care of this usecase?  Or would I need to use editor mode to set a new active area?  Or is there some other workflow I should consider?

**Comment by quietvoid** [comment]
You need to edit the RPU, see example: https://github.com/quietvoid/dovi_tool/blob/main/assets/editor_examples/active_area.json

**Comment by mylesmacrae** [comment]
Thanks!  Would the new active areas be relative to the new output video size?  i.e 0/0/0/0 for the 1.9 sequences, 208/0/208/0 for the 2.39 sequences?  Or would I keep the old values?

**Comment by quietvoid** [comment]
Yes.
You can then use `"crop": true` and only use one preset for 208/0/208/0 for the edits.

**Comment by mylesmacrae** [comment]
awesome.  thank you for the pointers!
