### ISSUE TITLE
Compare RPUs from Resolve 18.0 with implementation

### ISSUE THREAD

**Issue by quietvoid** [quietvoid/dovi_tool#153]
Blackmagic Design announced that DaVinci Resolve 18.0 Beta 2 now supports Dolby Vision output to MP4 using HEVC codec.

> Support for rendering Dolby Vision compatible H.265 clips.

It would be nice to compare our implementation, especially for `generate` with XML.
Anyone welcomed to try it out.

**Comment by saindriches** [comment]
With some tests on 18b2:
- The profile 5 output from Resolve doesn't do forward reshaping which DEE does, BL is just a normal IPTPQc2 video. Trim and L11 block is present.
- The 8.1 and 8.4 output from Resolve drops trim metadata, with predefined metadata instead.
- Windows platform needs a Dolby Vision license to use this feature (Don't know if it's just a bug or temporary limitation)

**Comment by imhh1** [comment]
> With some tests on 18b2:

@[saindriches](https://github.com/saindriches)
Hi, how do you deliver P5 / P8 mp4 in resolve ? I'm on 18B3 and I don't see any option to do that.
thank you!

**Comment by imhh1** [comment]
The main difference I'm noticing is that P8.1 mp4 from resolve has L4 metadata while the one we create from the XML file doesn't. Is L4 metadata present in the XML?

BTW it's working on a regular PC connected to an OLED without the  Dolby annual License. :)

**Comment by quietvoid** [comment]
L4 metadata is generated by analysis of the shot, it's not stored in the XML.

**Comment by quietvoid** [comment]
> Maybe it’s good to add a feature for `generate` to allow using L4 from an existing RPU as an _additional_ measurement source, just like madVR source.

I'm not sure what that means.

**Comment by saindriches** [comment]
I didn't say it correctly, don’t mind. I realized just use ```convert ``` should be enough. What I thought was add a feature to combine two RPUs, picking some blocks from one, and some blocks from the other one.

**Comment by quietvoid** [comment]
Some documentation: https://professionalsupport.dolby.com/s/article/Dolby-Vision-Encoding-using-Blackmagic-Design-DaVinci-Resolve-Studio-AQs
