### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Now2407** [quietvoid/dovi_tool#156]
Dolby vision from fel or Mel is not being injected into a new hevc track. The first file has the information but the rpu information is not present after conversion. I’m using profile 8.1 from 7, After checking with my Dolby vision tv I confirm it only shows as HDR10 and no Dolby vision. Does not mater witch commands I use. Please help, thanks!

**Comment by quietvoid** [comment]
> The first file has the information but the rpu information is not present after conversion.

Did you use MediaInfo on the output file? You need to mux it properly in mp4 or mkv.

As for your TV, figure out what format it supports.

This might be useful: https://www.avsforum.com/threads/authoring-dolby-vision-compatible-compliant-mp4-files-for-htpc-media-server-updated-05-01-2022.3212211/
