### ISSUE TITLE
Long play mode and alternative conditions

### ISSUE THREAD

**Issue by saindriches** [quietvoid/dovi_tool#160]
There is an undocumented option in verifier that allows checking user generated content from consumer devices like iPhone’s profile 8.4 video, named ```--alternative-conditions``` or ```-ac```, it supports ```ugch4_ios14```, ```ugch4_ios15``` etc. The ios14 mode requires ``` scene_reflash_flag```  always be ``` 1 ```, and actually it’s expected (but not limited) to be DM2 and only has L1 block. It’s also the behavior of some broadcasting devices, which only analyze frame based L1 values, in realtime. It’s a mode that RPU generated from this tool being considered as fully valid, it’s worth implementing this as an option. See [this branch](https://github.com/saindriches/dovi_tool/commits/profile-ac) 

Btw ugch4 modes have different recommended composer metadata values, and ios15 mode has strictly defined L8, L9, L10 and L11, different values will not pass the verifier. I don’t know if it’s worth implementing generating with ability to specify alternative conditions.

The recent version of Final Cut Pro also generates profile 8.4 video with ios15 condition, but Resolve beta on Windows doesn’t follow that.

**Comment by quietvoid** [comment]
Making specific presets for these "alternative conditions" isn't something I'm interested in.
It's all possible to do with the current generate config.

By default, iOS15 (my samples are only labeled iPhone 11 to 13) profile 8.4 look like:
- Default L3
- L9 with DCI-P3 D65 primaries
- Some automatically generated L8 for a 400 nits target
- L10 for 400 nits target, not sure what target display 20 is.
    - Not sure what target primary 2 is, maybe some real device DCI-P3.
- L11 with content type 4, UGC.

Do you plan on  creating a PR for the long play mode config? It's almost good enough but I was planning to do it anyways.

Also, I don't think profile 5 with profile 7/8 DM metadata is valid (especially the RGB coeffs).
Although Apple once made HDR10 profile 5 files, which I don't believe are valid.

**Comment by saindriches** [comment]
I didn't use the profile 8 coeffs for profile 5 in that commit, just used the default composer metadata of profile 8.1 (no reshaping), with correct IPT dm_data (coeffs).

**Comment by quietvoid** [comment]
You're right, I forgot I had done this already for `Profile5::dm_data`.

**Comment by ValZapod** [comment]
> * DCI-P3 D65 primaries

That is called P3-D65.
