### ISSUE TITLE
Duplicate L2 into L8 metadata when converting to CMv4.x

### ISSUE THREAD

**Issue by quietvoid** [quietvoid/dovi_tool#163]
If L8 is missing and the RPU is DM v2, the L2 has no effect (tested on LG C2)
If the target nits matches, we can use a target display ID, otherwise it probably requires creating a L10 block for it.

The issue is that L8 trim renders are very different with the same trim values as L2.

**Comment by saindriches** [comment]
Maybe it’s hard to achieve this, seems no patent describes L2 to L8 conversion they actually use. Basically it’s an algorithm matching the trim curves derived from one version to another, It also needs L1 / L3 for calculation iirc. It can be done with official tools though (needs metadata.xml)

**Comment by quietvoid** [comment]
IIRC metafier can convert XMLs between 2.9 and 4.x.
So it might be possible to figure out the relation between L2/L8

**Comment by quietvoid** [comment]
Seems only `trim_chroma_weight`, `trim_saturation_gain` and `ms_weight` map 1:1 from L2 to L8.

**Comment by quietvoid** [comment]
I don't think I'll try to do the L8 trims, so I'll be removing the convert to CMv4.x to avoid issues.

**Comment by quietvoid** [comment]
Removed the `convert_to_cmv4` option in 53d4b900620673d79d9d6ca32432064d769e5a7b
