### ISSUE TITLE
Add editing scene_refresh_flag value in RPU Editor

### ISSUE THREAD

**Issue by manuelrn** [quietvoid/dovi_tool#169]
Hi!

Would it be possible to implement scene_refresh_flag value to edit in the RPU Editor?

For example something similar to this:
```
    "scene_refresh_flag": {
        "all": boolean,
        "0-23": boolean,
        "123": boolean
    }
```
<br/>

Thanks and regards!

**Comment by quietvoid** [comment]
I'm not sure what use that would have but I suppose it could be done.

**Comment by quietvoid** [comment]
See example: https://github.com/quietvoid/dovi_tool/blob/main/assets/editor_examples/scene_cuts.json

**Comment by manuelrn** [comment]
Thank you very much @quietvoid!
