### ISSUE TITLE
Missing num_pivots_minus2[cmp]?

### ISSUE THREAD

**Issue by erazortt** [quietvoid/dovi_tool#171]
Following the patents and other sources I'm using, I think num_pivots_minus2[cmp] is missing from the output.

**Comment by quietvoid** [comment]
Which output?

**Comment by erazortt** [comment]
Oh sorry I found it.
I didn't find it right away because it is named num_pivots_minus_2. So it has an additional underscore between the "minus" and the "2". It would perhaps be nice if the namings of these minusX variables could be made consistent either with an underscore between the "minus" and the number or without.

**Comment by quietvoid** [comment]
Ah. It's a bit too late to change the name now.
I'd rather keep it like it is.
