### ISSUE TITLE
crop clarification

### ISSUE THREAD

**Issue by jriker1** [quietvoid/dovi_tool#172]
With the crop function, I am looking to take 4k HDR10/Dolby Vision content and re-encode it and crop off the black bars.  Below was my workflow and thinking it's now inaccurate after some conversations elsewhere: 

- demux original video track to HEVC (let's say it's 3840 x 2160 with 280 of black bars on top and bottom.)
- Run: dovi_tool extract-rpu <video>.h265
- Run: ffplay -i myfile -vf cropdetect to find the crop marks in this case 280 top and bottom.
- Run to convert: 
NVEncC64.exe --avhw --input <input_filename>.mkv --output <output_filename>.hevc --codec h265 --tier high --level 5.1 --output-depth 10 --cqp 19 --preset quality --vbv-bufsize 15000 --lookahead 32 --bframes 4 --aq-temporal --aud --repeat-headers --chromaloc 2 --colorprim bt2020 --transfer smpte2084 --colormatrix bt2020nc --colorrange limited --max-cll 413,65 --master-display copy --video-metadata copy --crop 0,280,0,280 --gop-len 0 --ref 3 --profile main10 --bref-mode middle --mv-precision Q-pel

- Run: dovi_tool inject-rpu -i video.hevc --rpu-in RPU.bin -o injected_output.hevc

I assume the above is incorrect however is it as simple as adding the -c option on the last inject step above?

**Comment by quietvoid** [comment]
> I assume the above is incorrect however is it as simple as adding the -c option on the last inject step above?

No. It should either be added to the first `extract-rpu` step or you can also edit the RPU afterwards.
Most global options have no effect when injecting.

Assuming you're reencoding a UHD BD, you also need to convert using mode 2.
