### ISSUE TITLE
dvhe and extracting dolby vision info?

### ISSUE THREAD

**Issue by jriker1** [quietvoid/dovi_tool#174]
I have an MP4 file that has an HEVC encoded video in it.  I extracted the video track and comes up as a DVHE file.  Tried running 

dovi_tool extract-rpu 

against it but gave a:

Error: Invalid input file type

Tried renaming the extension to H265 but gave a:

Error: get: out of bounds

Any idea what's up?  Never had a MP4 HEVC encoded file before, usually MKV so using different tools to extract but wasn't sure what I should be doing in this case.

Source info:
Video
Count                                    : 379
Count of stream of this kind             : 1
Kind of stream                           : Video
Kind of stream                           : Video
Stream identifier                        : 0
StreamOrder                              : 0
Inform                                   : English, 24.5 Mb/s, 3840*1918 (2.002), at 23.976 (24000/1001) FPS, HEVC (Main 10@L5@High), Dolby Vision
ID                                       : 1
ID                                       : 1
Format                                   : HEVC
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format/Url                               : http://www.itu.int
Commercial name                          : HEVC
Format profile                           : Main 10@L5@High
HDR format                               : Dolby Vision
HDR format                               : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
HDR_Format_Commercial                    : Dolby Vision
HDR_Format_Version                       : 1.0
HDR_Format_Profile                       : dvhe.05
HDR_Format_Level                         : 06
HDR_Format_Settings                      : BL+RPU
Internet media type                      : video/H265
Codec ID                                 : dvhe
Codec ID/Info                            : High Efficiency Video Coding with Dolby Vision
Duration                                 : 8817308
Duration                                 : 2 h 26 min
Duration                                 : 2 h 26 min 57 s 308 ms
Duration                                 : 2 h 26 min
Duration                                 : 02:26:57.308
Duration                                 : 02:26:59;12
Duration                                 : 02:26:57.308 (02:26:59;12)
Bit rate                                 : 24473134
Bit rate                                 : 24.5 Mb/s
Width                                    : 3840
Width                                    : 3 840 pixels
Height                                   : 1918
Height                                   : 1 918 pixels
Stored_Height                            : 1920
Sampled_Width                            : 3840
Sampled_Height                           : 1918
Pixel aspect ratio                       : 1.000
Display aspect ratio                     : 2.002
Display aspect ratio                     : 2.002
Rotation                                 : 0.000
Frame rate mode                          : CFR
Frame rate mode                          : Constant
Frame rate                               : 23.976
Frame rate                               : 23.976 (24000/1001) FPS
FrameRate_Num                            : 24000
FrameRate_Den                            : 1001
Frame count                              : 211404
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Chroma subsampling                       : 4:2:0
Bit depth                                : 10
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.139
Stream size                              : 26973394893
Stream size                              : 25.1 GiB (94%)
Stream size                              : 25 GiB
Stream size                              : 25 GiB
Stream size                              : 25.1 GiB
Stream size                              : 25.12 GiB
Stream size                              : 25.1 GiB (94%)
Proportion of this stream                : 0.93823
Language                                 : en
Language                                 : English
Language                                 : English
Language                                 : en
Language                                 : eng
Language                                 : en
Tagged date                              : UTC 2022-07-14 14:35:34
Menus                                    : 10
Codec configuration box                  : hvcC+dvcC

**Comment by Sawtaytoes** [comment]
What did you do to fix this?

I'm having the same error.

In my case, it's a Dolby Vision demo file.

MediaInfo is exactly the same between this `.ts` file and the other ones I remuxed into MKV. But this particular file loses Dolby Vision info when remuxing unlike the others.

I figured I could use `dovi_tool` to extract the Dolby Vision info and re-inject it into the MKV, but I need to figure out this error.
