### ISSUE TITLE
32 bits version

### ISSUE THREAD

**Issue by erazortt** [quietvoid/dovi_tool#177]
Would it be possible to also have a 32 bits version of libdovi?

**Comment by quietvoid** [comment]
I don't want to provide 32 bit builds.
You can try building it yourself.

**Comment by quietvoid** [comment]
I'll close this, let me know if you need help building.

**Comment by erazortt** [comment]
Yes, perhaps l you could describe what I’d need to do to build libdovi for 32 bits.

**Comment by quietvoid** [comment]
It's in the readme: https://github.com/quietvoid/dovi_tool/tree/main/dolby_vision
The rest is the usual Rust compilation setup, and building for the `i686-pc-windows-msvc` target.
