### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by chenyuanxu** [quietvoid/dovi_tool#179]
when i try to build this tool

PS D:\0insta\experiment\dovi_tool-main> cargo build --release
   Compiling dovi_tool v1.5.6 (D:\0insta\experiment\dovi_tool-main)
error: failed to run custom build command for `dovi_tool v1.5.6 (D:\0insta\experiment\dovi_tool-main)`

Caused by:
  process didn't exit successfully: `D:\0insta\experiment\dovi_tool-main\target\release\build\dovi_tool-f2d5df1864241a79\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: could not find repository from 'D:\0insta\experiment\dovi_tool-main'; class=Repository (6); code=NotFound (-3)', build.rs:10:20
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

how can i solve this problem?

**Comment by quietvoid** [comment]
Hm, that would be because the build requires that the git repo is present in the directory.

If you only downloaded the source zip, it wouldn't be.

I'll have to see how to fix that.

**Comment by quietvoid** [comment]
Should work now.
