### ISSUE TITLE
Compare profile 8.4 reshaping from iPhone 14's

### ISSUE THREAD

**Issue by quietvoid** [quietvoid/dovi_tool#182]
Apple possibly updated the Dolby Vision metadata from recordings using the iPhone 14.
The reshaping used currently is from iPhone 13, it might also be related to the iOS version.

Needs a sample to compare against.

**Comment by saindriches** [comment]
Apple updated the reshaping and dm data with the iOS15 release and recordings from iOS14 have older ones.

I got a sample from an iPhone 14 Pro. It seems the data hasn’t changed, it passes verifier with `-ac ugch4_ios15`.

**Comment by quietvoid** [comment]
Alright, it makes more sense that it's related to iOS.

Thanks for checking.
