### ISSUE TITLE
Error: Number of frames of input and RPU file are different!

### ISSUE THREAD

**Issue by Vortexar** [quietvoid/dovi_tool#19]
After successfully parsing RPU (8.1 Profile) from the source, I try to inject it then to my encode, but get an error "Thread main panicked at Number of frames of input and RPU file are different!, src/dovi/rpu_injector.rs:140:17".
The problem is that both source and encode has same number of frames, I checked it. But the error still exists.
I tried Dovi 0.3.2 and 0.3.1

**Comment by quietvoid** [comment]
Well the only other option is that the RPU has less "metadata" frames, or there's a bug with the HEVC parsing.

**Comment by ydajwz123** [comment]
I also encontered the same problem. I have tested two sources. Both behave similarly. (Use Makemkv latest version to make two layers MKV)
Note: As for source A, I also test a remux mkv from a famous group. The problem also remains.
The following is the procedure.
The command  `dovi_tool -c -m 2 extract-rpu BL+FEL+RPU.hevc` produces the RPU.bin. Further, I check the number of frames with command `dovi_tool info -i RPU.bin -f  INDEX_OF_FRAME`.
I found that the the number of frames from RPU is always one frame less than that of video file.
For example: `ffmpeg -map 0:v:0 -c copy -f null - -i BL+FEL+RPU.hevc` gives number of frame 161618.
`dovi_tool info -i RPU.bin -f 161616` is OK. 
`dovi_tool info -i RPU.bin -f 161617` will result in panick:
`Parsing RPU file...
thread 'main' panicked at 'assertion failed: f < rpus.len()', src\dovi\rpu_info.rs:23:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Although it is possible the source video is unreliable, I just talk about my experience for a reference.

**Comment by Vortexar** [comment]
> I also encontered the same problem. I have tested two sources. Both behave similarly. (Use Makemkv latest version to make two layers MKV)
> Note: As for source A, I also test a remux mkv from a famous group. The problem also remains.
> The following is the procedure.
> The command `dovi_tool -c -m 2 extract-rpu BL+FEL+RPU.hevc` produces the RPU.bin. Further, I check the number of frames with command `dovi_tool info -i RPU.bin -f INDEX_OF_FRAME`.
> I found that the the number of frames from RPU is always one frame less than that of video file.
> For example: `ffmpeg -map 0:v:0 -c copy -f null - -i BL+FEL+RPU.hevc` gives number of frame 161618.
> `dovi_tool info -i RPU.bin -f 161616` is OK.
> `dovi_tool info -i RPU.bin -f 161617` will result in panick:
> 
> ```
> Parsing RPU file...
> thread 'main' panicked at 'assertion failed: f < rpus.len()', src\dovi\rpu_info.rs:23:17
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Although it is possible the source video is unreliable, I just talk about my experience for a reference.

I checked my sources again and that is right - RPU is always one frame less than that of video file.
May be the problem is in RPU parsing?

**Comment by quietvoid** [comment]
It's quite likely to be a one off problem, however it feels a little odd that you can use the RPU file with x265, which verifies the number of RPUs against the frames encoded.

I'll try to reproduce with a full MakeMKV file.

**Comment by Vortexar** [comment]
> It's quite likely to be a one off problem, however it feels a little odd that you can use the RPU file with x265, which verifies the number of metadata frames against the frames encoded.
> It wouldn't fail but it should be warning.
> 
> I'll try to reproduce with a full MakeMKV file, but it would be useful to test with the same title.

The source file is 50GB big - would be not so easy to upload to some file hosting

**Comment by quietvoid** [comment]
@Vortexar I'm not asking for the file itself, just the title. I can buy it myself.

**Comment by Vortexar** [comment]
Aquaman (2018)

**Comment by quietvoid** [comment]
> For example: `ffmpeg -map 0:v:0 -c copy -f null - -i BL+FEL+RPU.hevc` gives number of frame 161618.

I'm not sure FFmpeg is accurate with this command line.
I have piped from a MakeMKV remux as well as demuxed the video, and the number of frames was always correct.

With your command, the number of frames is increased by 1.
FFmpeg also errored: `[NULL @ 0x55660d526a40] missing picture in access unit with size 287`

So both piping & demuxing with `ffmpeg -i title_t00.mkv -c:v copy video.hevc` resulted in `frame=189716`
While your command results in `frame=189717`, and is incorrect.

The RPU contains 189716 metadata frames, so that's correct.
And I can do `dovi_tool info -i RPU.bin -f 189715`, which is fine because the `-f` parameter starts at 0.

**Comment by quietvoid** [comment]
I did a `dovi_tool inject-rpu -i BL.hevc --rpu_in RPU.bin` and it worked perfectly fine.

So I can't reproduce the issue here.

**Comment by ydajwz123** [comment]
> 
> 
> > For example: `ffmpeg -map 0:v:0 -c copy -f null - -i BL+FEL+RPU.hevc` gives number of frame 161618.
> 
> I'm not sure FFmpeg is accurate with this command line.
> I have piped from a MakeMKV remux as well as demuxed the video, and the number of frames was always correct.
> 
> With your command, the number of frames is increased by 1.
> FFmpeg also errored: `[NULL @ 0x55660d526a40] missing picture in access unit with size 287`
> 
> So both piping & demuxing with `ffmpeg -i title_t00.mkv -c:v copy video.hevc` resulted in `frame=189716`
> While your command results in `frame=189717`, and is incorrect.
> 
> The RPU contains 189716 metadata frames, so that's correct.
> And I can do `dovi_tool info -i RPU.bin -f 189715`, which is fine because the `-f` parameter starts at 0.
> According to the video length, the correct number of frames is also 189716.
> 
> I still have to test demuxing into BL+EL and reinjecting, but I'm not really seeing any use case for this.

THANKS. I found the problem is related to the way I demux the BL+FEL+RPU.mkv. I previously use gMKVExtractGUI. Currently, I will turn to ffmpeg.
BTW, the counting of number of frames is actually correct, but the BL+FEL+RPU.hevc by gMKVExtractGUI seems corrupt so that dovi_tool cannont extract a correct RPU.

**Comment by Vortexar** [comment]
The issue can be closed now. The problem is really in bad initial demux. Eac3to and MKVExtract break RPU data while demuxing, making it one frame less.
I reripped disc and demuxed with Ffmpeg - everything is ok

**Comment by quietvoid** [comment]
I just got around to testing `inject-rpu` on a very quick Aquaman (2018) encode and it worked fine as well.
