### ISSUE TITLE
Optimize the performance

### ISSUE THREAD

**Issue by quietvoid** [quietvoid/dovi_tool#2]
The current parsing is very inefficient, it always copies the data around.
There is ongoing work in a branch, to use `nom` and avoid copying data as much as possible.

**Comment by ghostshadow83** [comment]
Hello quietvoid and thank you for your software, could you if you don't mind implementing a configurable file output 👍  
outputFile=
Thank you!

**Comment by quietvoid** [comment]
@ghostshadow83 Read the help, there are already command line arguments to specify the output files.

**Comment by ghostshadow83** [comment]
Ok so much for me sorry I was doing dovi-tools --help only
thank you

**Comment by hyllm** [comment]
> 
> 
> @ghostshadow83 Read the help, there are already command line arguments to specify the output files.

I cannot find how to set output file also... -o not working...

**Comment by quietvoid** [comment]
Please stop using this issue for general questions.
You can do `dovi_tool subcommand --help`
For example, `dovi_tool demux --help`

**Comment by hyllm** [comment]
> 
> 
> Please stop using this issue for general questions.
> You can do `dovi_tool subcommand --help`
> For example, `dovi_tool demux --help`

Thanks and sorry

**Comment by quietvoid** [comment]
A first attempt with just using nom for the NAL parsing:

SATA SSD
main: 452.95s user 17.26s system 98% cpu 7:59.71 total
switch_to_nom2: 31.67s user 23.82s system 40% cpu 2:18.58 total

NVME SSD
main: 452.90s user 17.90s system 99% cpu 7:53.56 total
switch_to_nom2: 31.68s user 24.38s system 61% cpu 1:30.81 total

**Comment by quietvoid** [comment]
Even though I made `extract-rpu` slower for reordering properly, I'm pretty happy with the performance for now.
