### ISSUE TITLE
Is there any limit of crop height?

### ISSUE THREAD

**Issue by ydajwz123** [quietvoid/dovi_tool#21]
This issue may be not related to dovi_tool itself. But I wonder how to correctly crop, resize and transcode the DoVi video.
When I mux cropped&resized&transcoded BL+RPU.hevc (profile 8.1) to the container (MKV or MP4). The height of the video is automatically changed to a number that mod 8. 
For example, The original height is 1038. After demuxing, alghough the "HDR format" is expected to be Dolby vision and HDR10 compatible, the "Height" changed to 1040 and size of the whole file also grows by about 600MB. （By MakeMKV）
I currently only knows to use MakeMKV, tsMuxer or mp4muxer to add the Dolby Vision information to the HEVC codestream.

**Comment by quietvoid** [comment]
If you're using MakeMKV, it is modifying the resolution to be mod 8.
I don't know why the file size would increase though.

MKVToolNix support was added in the main branch, so possibly in the next version it will be usable instead of relying on MakeMKV.

**Comment by ydajwz123** [comment]
THANKS for quick reply.
BTW, when I play the video (potplayer or MPV), both source screenshot or display screenshot show that the height is 1038. It seems there is nothing to do with "Height" in header. Can I just edit the header information by MKVToolNix?

**Comment by quietvoid** [comment]
Yes it should be fine to do, the HEVC stream might still be affected though.
