### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by sagz** [quietvoid/dovi_tool#22]
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/964843/120875287-f7822a80-c55f-11eb-9532-1bba3c8820fa.png">

Error:
```
>dist ./dovi_tool extract-rpu img_5858.hevc   
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/runner/.cargo/registry/  
src/github.com-1ecc6299db9ec823/bitvec_helpers-0.1.0/src/bitvec_reader.rs:21:44
```

This is the hevc file I extracted out of an iPhone 12 DoVi encoded file (8.4 I believe).

The `.hevc` file was extracted out of the `.mov` container with `ffmpeg -i ~/Pictures/IMG_5858.MOV -c:v copy -vbsf hevc_mp4toannexb -f hevc img_5858.hevc`

**Comment by quietvoid** [comment]
I'm pretty sure it's working in master, because there's a bug in the previous hevc_parser version.
Can you test it?

Not much I can do otherwise without a sample.

**Comment by sagz** [comment]
I tried the build from Master (https://github.com/quietvoid/dovi_tool/actions/runs/814558437) and got the same error.

Here's the original video file: https://github.com/sagz/files/releases/download/v0.1/IMG_5858.MOV
I extracted the hevc stream out with `ffmpeg -i IMG_5858.MOV -c:v copy -vbsf hevc_mp4toannexb -f hevc img_5858.hevc`

**Comment by quietvoid** [comment]
That's not an up to date build. You would have to build from source.
I just tried with the file and it works on commit 1cffc610997a0bb19dac750dcdf6842700513688

So I guess I'll just bump the version and update releases.

**Comment by quietvoid** [comment]
Please test this: https://github.com/quietvoid/dovi_tool/releases/tag/0.3.3

**Comment by sagz** [comment]
Yep, I was able to extract it! Thanks! :)
