### ISSUE TITLE
Improve RPU file loading to remove hard 250M file size limit

### ISSUE THREAD

**Issue by quietvoid** [quietvoid/dovi_tool#221]

**Comment by zuba0012** [comment]
#225 Created change to address issue #221.

**Comment by zuba0012** [comment]
Seems like a similar file size hard limit may happen with madVR measurement files, so probably can expand scope of this issue to include other input files.

**Comment by quietvoid** [comment]
Yes, it's the same issue.

**Comment by Sawtaytoes** [comment]
Is it possible this could be changed? I'm running into the same issue.

Is it a memory overflow issue or a safety check?

**Comment by quietvoid** [comment]
It's a safety check because currently the RPU is loaded entirely in memory.
