### ISSUE TITLE
Improper extraction

### ISSUE THREAD

**Issue by jpsdr** [quietvoid/dovi_tool#230]
Hello.
I have an extracted DV stream, that when i convert with -m 2, seems to behave improperly.
I can provide you the extracted stream on my ftp server, contact me at jpsdr.psx@free.fr.

**Comment by quietvoid** [comment]
Seems to behave improperly? What does it do?

**Comment by jpsdr** [comment]
The progress stop at 34%, and the output file created is obviously too small.

**Comment by jpsdr** [comment]
An error on the HDD is not something you think/expect, anyway, redone the extract and everything was fine, so i close.
And big thanks for the tool !
