### ISSUE TITLE
[feature] Add remove command

### ISSUE THREAD

**Issue by cromefire** [quietvoid/dovi_tool#232]
It would be really nice if there would be a remove command similar to the `remove` command in `hdr10plus_tool` that removes dolby vision metadata from the stream. I have some files with seemingly damaged dolby vision metadata, so it would be nice to be able to remove it without needing to transcode them.

**Comment by quietvoid** [comment]
This is already supported through `demux`.
But maybe it could be worth having a `remove` subcommand as well.

**Comment by cromefire** [comment]
You are completely right didn't notice the little notice:

>  Also can be used to remove the RPUs from an HEVC file.

Maybe an example with a remove heading in the README or a remove "shortcut" could be nice though. Because right now from the README I'm not quite sure whether just a normal demux already removes if or whether I need any specific flag or so, because from the description it only removes the EL, but I have files with profile 8.1, so as far as I understand there is no EL. Might just be a little deficiency in documentation.
