### ISSUE TITLE
TSMuxer import or EL issue?

### ISSUE THREAD

**Issue by quamt** [quietvoid/dovi_tool#236]
Hello,

I am not sure if I do something wrong but I get a error message when I try to import the extracted EL.hevc into TSmuxer.

I try converting from DoVi 5 to 7 which will create a BL.hevc and an EL.hevc.
When importing the BL all is good but the EL gives an error that it can't read the file.

Any help would be appreciated. 

Thank you.

**Comment by quietvoid** [comment]
Profile 5 does not have an EL.
