### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by phodina** [quietvoid/dovi_tool#238]
Hi,
I'm porting this package to Alpine Linux.

When running the test suite I get this failing test.

Could you please suggest how to fix the error?
```
test rpu::plot::plot_p7 ... FAILED

failures:

---- rpu::plot::plot_p7 stdout ----
thread 'rpu::plot::plot_p7' panicked at 'Unexpected stderr, failed var.is_empty()
├── var: Fontconfig warning: ignoring UTF-8: not a valid region tag
└── var as str: Fontconfig warning: ignoring UTF-8: not a valid region tag

command=`"/home/pmos/build/src/dovi_tool-2.0.3/target/release/dovi_tool" "plot" "assets/hevc_tests/regular_rpu.bin" "--output" "/tmp/.tmpQhvByJ/L1_plot.png"`
code=0
stdout=```
Parsing RPU file...
Plotting...
Done.
```

stderr="Fontconfig warning: ignoring UTF-8: not a valid region tag\n"
', /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    rpu::plot::plot_p7

test result: FAILED. 60 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.27s
```

**Comment by quietvoid** [comment]
There's an issue in your system locales so Fontconfig is complaining.
It has nothing to do with `dovi_tool`.

You can search the `ignoring UTF-8: not a valid region tag` warning and find solutions easily.
