### ISSUE TITLE
RPU.bin max file size is 25.5M?

### ISSUE THREAD

**Issue by nsonline** [quietvoid/dovi_tool#25]
If the extracted RPU file size is smaller than 25.5M, all the complete information can be saved normally.
However, the RPU files saved by some film will be relatively large, exceeding 25.5M, so the final RPU file obtained is only 25.5M.

I used <Raiders of the Lost Ark 1981> and <Indiana Jones and the Temple of Doom 1984> to test , and I can only save 25.5M RPU file at most, which probably stores more than 70,000 frames of information. Some other movies are no problem, because the final RPU file saved does not reach 25.5M.
The test environment is Windows 10, using CMD to run `dovi_tool -m 2 extract-rpu video.hevc` to extract the RPU information.
Is there a problem with my environment?

**Comment by quietvoid** [comment]
What happens when the file is over the size?

There is no maximum number of frames or max RPU file size.
