### ISSUE TITLE
inject-rpu on AV1 (SVT) fails

### ISSUE THREAD

**Issue by jaschx** [quietvoid/dovi_tool#254]
Hello,

i am not 100% sure if this is supported, but i have seen Changes for DV support on AV1 in Code.
dovi_tool 2.0.3 (compiled today 16.09.23 from source)

When i try to inject RPU in to a AV1 encoded file -> "Error: Invalid PPS index ".

What i did: 
Demuxed DV RPC from File.
Encode File with Handbrake 1.61 AV1 10-bit (SVT). (encoded File runs HDR10)
Try to inject -> Error

Same File encoded with h.265 10-bit, inject works fine.

wbr Alex, and thx for your work

**Comment by quietvoid** [comment]
I don't know why you'd expect it to work.
AV1 is not supported currently.

**Comment by jaschx** [comment]
Because i saw this, but i missunderstood it. (sorry for spelling i am not a native englisch speaker)
https://github.com/quietvoid/dovi_tool/pull/244/commits/0a43a3a5127b2839e4793ea98a242cddbb979051

**Comment by quietvoid** [comment]
It's not support for AV1 files.

**Comment by quietvoid** [comment]
Not to my knowledge.
