### ISSUE TITLE
Please support injecting RPU into HLS streams

### ISSUE THREAD

**Issue by venomone** [quietvoid/dovi_tool#255]
Hello,

is it possible that we inject RPU data into segmented HLS streams using fmp4 HEVC format ? Would be awesome to have
and it also would close the issue that ffmpeg does not support the dolby-vision-rpu libx265-params option yet.

Thanks in advance

**Comment by quietvoid** [comment]
> is it possible that we inject RPU data into segmented HLS streams using fmp4 HEVC format ?

No, only raw bitstream without a container is and will ever be supported for `inject-rpu`.
