### ISSUE TITLE
HDR10+ from DV json

### ISSUE THREAD

**Issue by Gedeon90** [quietvoid/dovi_tool#260]
Hi. 
Firstly congrats for your tool.

Two years later one user asked you about the chances of building HDR10+ from DV , I just wonder if now is possible /easier to enter into this.

I also guess this post (https://www.reddit.com/r/ffmpeg/comments/14bbelj/so_you_can_convert_dolby_vision_to_hdr10_and_visa/) isn't correct at all, but other projects, like libplacebo seems to be able to build HDR10 headers using DV metadata.

It would be really great to get a way to achieve this: DV to HDR10+

Thanks!

**Comment by quietvoid** [comment]
HDR10+ needs the brightness histogram, which isn't possible to compute solely from Dolby Vision metadata.
It would always require measuring the actual video brightness, which is out of scope for this project.
