### ISSUE TITLE
Add support for Dolby Vision profile 20

### ISSUE THREAD

**Issue by quietvoid** [quietvoid/dovi_tool#263]
Samples: https://developer.apple.com/streaming/examples/

**Comment by saindriches** [comment]
It seems like verifier cli (v4.5.0) doesn't support it yet.

**Comment by quietvoid** [comment]
Yes it is mentioned in the Dolby page.
> Dolby Vision Verification Toolkit: Currently Available upon request

**Comment by quietvoid** [comment]
The only difference seems to be that `el_bit_depth_minus8=58370` is failing validation but if ignoring the rest parses fine.

**Comment by Nomis101** [comment]
There is now support for el_bit_depth_minus8 and ext_mapping_idc in FFmpeg.
https://github.com/FFmpeg/FFmpeg/commit/0c0e7ec81e9f05aa09db5c730e2661d0b2eeb72c

**Comment by quietvoid** [comment]
I guess I'll merge the PR with the FFmpeg naming.
