### ISSUE TITLE
Add support for Dolby Vision Profile 9 (MPEG-4 AVC Dolby Vision, backwards compatible with SDR)

### ISSUE THREAD

**Issue by Hydra-Spectre** [quietvoid/dovi_tool#270]
I hope this can be added.
It would be a real boon for films and shows that are only 1080p Dolby Vision on streaming, and they have a Blu-ray release with higher bitrates.

**Comment by quietvoid** [comment]
Profile 9 is basically nonexistent in the real world, so it's unlikely to get supported.
