### ISSUE TITLE
Documentation might need updated 

### ISSUE THREAD

**Issue by jlw4049** [quietvoid/dovi_tool#273]
I was trying to utilize this command 
`ffmpeg -i input.mkv -c:v copy -vbsf hevc_mp4toannexb -f hevc - | dovi_tool demux -` 
on newer versions of FFMPEG and getting the error `Unrecognized option 'vbsf'.`.

Looks like FFMPEG no longer supports this and expects `bsf` in it's place. 

In the [documentation](https://ffmpeg.org/ffmpeg-bitstream-filters.html#toc-hevc_005fmp4toannexb) it shows an example: 
`ffmpeg -i INPUT.mp4 -codec copy -bsf:v hevc_mp4toannexb OUTPUT.ts`

**Comment by quietvoid** [comment]
They were deprecated long ago and recently got completely removed.
