### ISSUE TITLE
Feature: Provide frame numbers in RPU.json

### ISSUE THREAD

**Issue by aboulfad** [quietvoid/dovi_tool#275]
Hello,

I sometimes want to check individual frames metadata, the only way I found was to specify the frame using info -f.  However, it would be very useful if the RPU.json file contained frame numbers (via an option so not to impact current behaviour).

It's possible I missed another method to accomplish the above, thank you.

**Comment by quietvoid** [comment]
The full RPU.json export is not intended to be human readable, you should be able to easily script something.
It's a JSON array.

For example with `jq` you can do `jq '.[index]' RPU_export.json` where `index` is the frame number.
