### ISSUE TITLE
Argument '--rpu-in' instead of '--rpu_in'

### ISSUE THREAD

**Issue by manuelrn** [quietvoid/dovi_tool#28]
In the `inject-rpu` documentation, the example has `--rpu-in` argument, but it doesn't work and you need to use `--rpu_in`.

I think the ideal would be to change the argument to `--rpu-in`, instead of updating the documentation with `--rpu_in`, since all other arguments are also `-` and not `_` (`--rpu-out`, `extract-rpu`).

Thanks and regards!

**Comment by quietvoid** [comment]
Indeed, that was pointed to me. I'll fix it.
