### ISSUE TITLE
Request: Print out the crop values for the active area offsets

### ISSUE THREAD

**Issue by Dendraspis** [quietvoid/dovi_tool#280]
Hello quietvoid,

when using the `--crop`/`-c` parameter when extracting the rpu data like so:
`ffmpeg.exe -i "Hybrid HDR10Plus DV Sample.mkv" -an -sn -dn -c:v copy -bsf:v hevc_mp4toannexb -f hevc - | dovi_tool.exe -m 2 -c extract-rpu - -o "RPU.bin"`
...the only information provided is:
`Reordering metadata... Done.`

It would be nice and useful to get information about the crop values, so they can be used for further processing. 
Something like:
```
Reordering metadata... 
Offsets were cropped by: left=0, right=0, top=276, bottom=276
Done.
```

In this context I have also a question:
Where does `dovi_tool` take the values, to crop the offsets, from or how are they calculated?

**Comment by quietvoid** [comment]
It's an extract operation and not meant to show any info.
Use the appropriate subcommand to get offsets info:
```
dovi_tool export -i RPU.bin -d level5
```

**Comment by Dendraspis** [comment]
Okay, thanks anyway.

> There's no calculation, `--crop` simply sets the L5 metadata to all zeros.

That was actually pretty helpful, thank you.
