### ISSUE TITLE
Re-encoded material not working

### ISSUE THREAD

**Issue by tinyknilch** [quietvoid/dovi_tool#30]
Ripped Indiana Jones Collection 4K to HDD (tested with LOST ARK and TEMPLE OF DOOM) with MakeMKV backup function, then demuxed m2ts into BL + EL with FFMPEG. Encoded BL with the help of RipBot264 into a 22 GB HDR10 BL. Then tried to do a MUX_AND_CONVERT_TO_MEL with the encoeded BL and the original EL. Does not work - BL_ANALYIS increases with rapid speed until 100% is reached. That time EL_ANALYSIS shows 4,2% and stops the moment BL reaches 100%. Been waiting now for 2 more hours without any further progress. Tested the original BL and EL, which worked without any problems. Any ideas?
![screenshot](https://user-images.githubusercontent.com/88186777/127635038-e59ba5f2-ba90-4708-9881-e5658dece26c.jpg)

**Comment by quietvoid** [comment]
This is not the place to get support on yusesope's tools.
