### ISSUE TITLE
Corrupt video stream when converting a specific P7 MEL clip to P8

### ISSUE THREAD

**Issue by adam1x** [quietvoid/dovi_tool#300]
Here's a 10-second Profile 7 MEL clip that consistently generates a corrupt video stream upon conversion to Profile 8: https://drive.proton.me/urls/97JT3QWXWG#okXHm6tZieZB

The Profile 7 clip plays fine everywhere, while the resulting Profile 8 clip freezes a few seconds in. I tested on MPC-BE & VLC on PC and on a Zidoo Z9X.

The clip is from [StudioCanal's The Servant UHD BD](https://www.blu-ray.com/movies/The-Servant-4K-Blu-ray/288515/), 1.75:1 aspect ratio version. Ripped from my own disc and sampled 00:18:05 to 00:18:15. The full corruption lasts from 00:18:09 to 00:36:05 when I convert the entire film. The disc itself plays without a hiccup in DV.

Converted to P8 with:

- DoVi_Scripts 2.0.4
- tsMuxer [git-acdfe54](https://github.com/justdan96/tsMuxer/releases/tag/nightly-2024-04-06-01-50-49) (nightly build on April 6)
- ffmpeg 7.0-full_build
- dovi_tool 2.1.1

I'm not sure whether it's a bug in dovi_tool or ffmpeg. Filing here for an initial look. Thanks!

**Comment by quietvoid** [comment]
It's caused by FFmpeg.

When I just demux the original profile 7 MEL bitstream, the issue is present.
```
ffmpeg -i The.Servant.1963.2160p.StudioCanal.1.75AR_chunk_P7.MEL.mkv -c copy video.hevc
```

It works fine with `mkvextract`.
