### ISSUE TITLE
Entry point of ProcessPrng can't be found on bcryptprimitives.dll

### ISSUE THREAD

**Issue by jpsdr** [quietvoid/dovi_tool#307]
Hello.

I have the error message "Entry point of ProcessPrng can't be found on bcryptprimitives.dll" with the last 2.1.2 version.
Work fine with previous 2.1.1 version.

**Comment by quietvoid** [comment]
The published binary targets Windows 10 s minimum supported version, since Rust 1.78.0.

You need to build your own if your Windows is older.
See https://blog.rust-lang.org/2024/02/26/Windows-7.html
