### ISSUE TITLE
ARM64 Windows version/build

### ISSUE THREAD

**Issue by Professio73** [quietvoid/dovi_tool#308]
Any chance on a version/build for ARM64 on Windows?

**Comment by quietvoid** [comment]
Would need to test cross compiling but GitHub does not currently offer ARM runners for open source projects.

**Comment by quietvoid** [comment]
Are you able to test the Windows aarch64 build?
It's available in the artifacts here: https://github.com/quietvoid/dovi_tool/actions/runs/10539437840

- Download `Windows artifacts`
- Extract from the downloaded `Windows artifacts.zip` file
- Extract the `dovi_tool` executable from `dovi_tool-2.1.2-aarch64-pc-windows-msvc.zip`
- Test that it works OK.

**Comment by Professio73** [comment]
yes, seems to work fine. tested `convert`, `extract-rpu` and `plot` commands. so far so good 👌

**Comment by quietvoid** [comment]
Thanks.

**Comment by quietvoid** [comment]
I've updated the `2.1.2` release with the ARM64 for Windows and Linux executables.
