### ISSUE TITLE
Error extracting Dovi data from "The Fate of the Furious (2017)" and "The Hitmans Bodyguard (2017)"

### ISSUE THREAD

**Issue by NZDivinity** [quietvoid/dovi_tool#31]
I've ran into an issue trying to extract(& convert to MEL) the dovi data from both the above movies.
I use the following command to pipe from ffmpeg to dovi_tool version 0.3.5. Both are FEL movies.

ffmpeg -i "K:\00234.m2ts" -map 0:1 -c:v copy -an -vbsf hevc_mp4toannexb -f hevc - | dovi_tool -m 1 extract-rpu - --rpu-out "K:\RPUMEL.bin"

I get the following error :
thread 'main' panicked at 'Range 7..13 out of bounds: 8', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\bitvec-0.20.2\src\slice\api.rs:2651:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Exact sources used : 
The.Fate.of.the.Furious.2017.2160p.BluRay.HEVC.DTS-X.7.1-HDRINVASION
The.Hitmans.Bodyguard.2017.2160p.BluRay.HEVC.TrueHD.7.1.Atmos-TERMiNAL

Thanks in advance

**Comment by quietvoid** [comment]
Extracting an RPU from a EL video stream is not supported.
This is what you're doing by using a m2ts and piping the data from the 2nd video track.

**Comment by NZDivinity** [comment]
Ah I see.
Would you be able to let me know the proper workflow for extracting RPU data please?

I've tried extracting from an MKV created from MakeMKV, which works.. but the RPU data is a different amount of frames to the x265 encoded file I have(which was sourced from the same MKV). Reason I don't inject the RPU while encoding is that Hybrid doesn't currently support profile 4.

**Comment by quietvoid** [comment]
There should be nothing wrong with extracting from a MakeMKV file.
If you have different frame numbers, refer to the discussion here: https://github.com/quietvoid/dovi_tool/issues/24

The gist of it is to use either MKVToolNix's mkvextract or ffmpeg.
