### ISSUE TITLE
Some global options are described by `dovi_tool --help` in a way that leaves it unclear which commands they actually work with

### ISSUE THREAD

**Issue by damster101** [quietvoid/dovi_tool#312]
For `--drop-hdr10plus` and `--start-code` I don't see an issue, the description makes it obvious that it will only work with commands `inject-rpu` and `convert`. Didn't test if that's actually the case, though.

But, `--crop` works with command `extract-rpu`, but not `export` or `generate`. Didn't try others. But I assume that it works with `convert` as well, since it seems to do something during RPU extraction. But from the description alone all this is not obvious, so users might expect for it to work with commands where it actually doesn't do anything.

Then there is `--mode`, which I'm not sure when it does something, as I haven't tested it. I think "RPU processing" is not explicit enough there.

**Comment by quietvoid** [comment]
PRs welcome to improve documentation.
The "global" options have an effect for HEVC processing only.

**Comment by damster101** [comment]
Alright, that's good to know. I'll think about how documentation can be best improved, and will probably make a PR then.
