### ISSUE TITLE
Editor: duplicate metadata does not append if offset is the last frame

### ISSUE THREAD

**Issue by tricktron** [quietvoid/dovi_tool#320]
Hello @quietvoid

First of all, thank you for your amazing work. While playing around with the editor command I noticed the following edge case:

You cannot append frames at the end with duplicate: e.g. with `[ x, y ]` frames and the following `duplicate.json`:
```json
{
    "duplicate": [
        {
            "source": 0,
            "offset": 1,
            "length": 1
        }
    ]
}
```

Current result:
`[ x, x, y ]`

Expected result:
`[ x, y, x ]` 

I think the problem is the following guard:

https://github.com/quietvoid/dovi_tool/blob/2cde6817badba832fc1d139f18e0857130f08741/src/dovi/editor.rs#L338-L338

and the following splice function:
https://github.com/quietvoid/dovi_tool/blob/2cde6817badba832fc1d139f18e0857130f08741/src/dovi/editor.rs#L344-L347

If you want to add at the end then it should be `len(data)..len(data)` and for this to work the guard should be `meta.source < data.len() && meta.offset <= data.len()`. 

Beware, that I am no rust expert but if I find some time I might come up with a test case and a pull request over the weekend.

**Comment by quietvoid** [comment]
You're right, it is currently not possible to append.
It only needs the guard to be changed to `<=`.
