### ISSUE TITLE
Panic in syn crate when building libdovi

### ISSUE THREAD

**Issue by Uranite** [quietvoid/dovi_tool#324]
#### Steps to Reproduce
1. Clone the repo
2. Navigate to the directory `dolby_vision`
3. Run the following:
   ```bash
   cargo cinstall --release
   ```
4. The build process begins, successfully compiling dependencies, but fails with the following error:
   ```
   thread 'main' panicked at C:\Users\<username>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\syn-1.0.109\src\lit.rs:1020:13:
   Unrecognized literal: c"FEL"
   note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
   ```
#### Observed Behavior
The build process completes the compilation of dependencies and initial steps, but it seems to fail during the building of the header files, resulting in no header files created.
#### Expected Behavior
The build process should complete successfully without panics.
#### Environment
- Windows 11
- Rust Version: 1.83.0
#### Log
```bash
> cargo cinstall --release
   Compiling radium v0.7.0
   Compiling libc v0.2.167
   Compiling anyhow v1.0.93
   Compiling tap v1.0.1
   Compiling bitstream-io v2.6.0
   Compiling funty v2.0.0
   Compiling crc-catalog v2.4.0
   Compiling tinyvec v1.8.0
   Compiling crc v3.2.1
   Compiling wyz v0.5.1
   Compiling bitvec_helpers v3.1.6
   Compiling bitvec v1.0.1
   Compiling dolby_vision v3.3.1 (D:\<username>\official_test_place\temp\dovi_tool\dolby_vision)
    Finished `release` profile [optimized] target(s) in 4.04s
    Building pkg-config files
    Building .def file using dumpbin
    Building implib using lib
    Building header file using cbindgen
thread 'main' panicked at C:\Users\<username>\.cargo\registry\src\index.crates.io-6f17d22bba15001f\syn-1.0.109\src\lit.rs:1020:13:
Unrecognized literal: `c"FEL"`
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by quietvoid** [comment]
Something is wrong with your dependency versions, `syn` should be at least version `2.0.74` and it's  only `1.0.109` in your build.
Also, make sure your `cargo-c` is up to date.

**Comment by Uranite** [comment]
> Also, make sure your `cargo-c` is up to date.

Thanks, updating `cargo-c` fixed it
