### ISSUE TITLE
"crop" in dovi metadata?

### ISSUE THREAD

**Issue by hyllm** [quietvoid/dovi_tool#39]
Are there any "crop" or "black bars signaling" tags in DoVi metadata??? Because when I encode video (using BIN directly with x265), in HDR10/HDR10+ file plays OK, but with DoVi (Plex on Android TV, Kodi on Adroid TV and also internal media player), file is playing perfectly, trigerring Dolby Vision, but, it runs like cropped again... na dimensions change, but as DoVi meta tells to TV to crop part of played picture. When I encode same movie with same BIN file uncropped, everything is 100% OK.

If so... is there possibility to remove the by me so called "crop flag"?

**Comment by hyllm** [comment]
oh.. i found "-c" option... :) is that a solution? :)

**Comment by quietvoid** [comment]
`--crop` should be used when the final video has no letterbox bars, otherwise there could be artifacts or overcropping on playback.

**Comment by hyllm** [comment]
just one more question. :)

active area is set for the screen, or picture... for example, if i encode at 1920x1080, should I edit active area to half values, or it is counted as played on 3840x2160 TV so it will be the same....

**Comment by quietvoid** [comment]
The values should be in respect to the video's native resolution. Not upscaled.

**Comment by hyllm** [comment]
so when I resize 3840x2160 to 1920x1080, I should edit active area offsets to half, of the original? But will the DoVi metadata be accurate?? Meaning overall... if the dimensions are changed...

**Comment by quietvoid** [comment]
You should edit the offsets to be equal to the letterbox bars width at 1920x1080, yes.
Resolution should not make a difference.

**Comment by hyllm** [comment]
Thank you very very very much for kind answers. :) Are you accepting donations for DoVi Tool and HDR10+ parser (btw, with HDR10+, it's no matter, if resizing and cropping, right?)?

**Comment by quietvoid** [comment]
Not accepting donations.
HDR10+ is the same principle.

**Comment by hyllm** [comment]
afaik, hdr10+ has no active area offset, so no need to edit... roght?

**Comment by quietvoid** [comment]
Correct

**Comment by jeremysgates** [comment]
> `--crop` should be used when the final video has no letterbox bars, otherwise there could be artifacts or overcropping on playback.

To clarify on this statement.  Do I understand correctly that if I encode my UHD HDR10 video with x265 cropping out the top and bottom letterbox bars out (i.e. 280 px top  & 280 px bottom for example), that I am correct in using the --crop option when extracting the RPU/converting to profile 8.1 compatible?

Since I'm cropping the letterbox bars out during the encode, the way I'm reading your statement above, I should use --crop when extracting/converting the RPU from my source DV Profile 7 source.

The part I'm having trouble with is how using --crop when extracting the RPU from the source DV 7 file "knows" the correct size of the letterbox bars to crop. (I'm cropping the BL HDR10 video during the x265 encode and NOT doing any downscaling).   

Or am I reading your statement totally wrong?   Thanks for any clarification and for the most excellent tools!

**Comment by quietvoid** [comment]
>  Do I understand correctly that if I encode my UHD HDR10 video with x265 cropping out the top and bottom letterbox bars out (i.e. 280 px top & 280 px bottom for example), that I am correct in using the --crop option when extracting the RPU/converting to profile 8.1 compatible?

Yes.

> The part I'm having trouble with is how using --crop when extracting the RPU from the source DV 7 file "knows" the correct size of the letterbox bars to crop. (I'm cropping the BL HDR10 video during the x265 encode and NOT doing any downscaling).

It has no knowledge of the letterbox bars size, they are simply set to zero, to tell the Dolby Vision decoder that there are no letterbox bars encoded in the video.

**Comment by jeremysgates** [comment]
> > Do I understand correctly that if I encode my UHD HDR10 video with x265 cropping out the top and bottom letterbox bars out (i.e. 280 px top & 280 px bottom for example), that I am correct in using the --crop option when extracting the RPU/converting to profile 8.1 compatible?
> 
> Yes.
> 
> > The part I'm having trouble with is how using --crop when extracting the RPU from the source DV 7 file "knows" the correct size of the letterbox bars to crop. (I'm cropping the BL HDR10 video during the x265 encode and NOT doing any downscaling).
> 
> It has no knowledge of the letterbox bars size, they are simply set to zero, to tell the Dolby Vision decoder that there are no letterbox bars encoded in the video.

Excellent!  Thanks so much for the clarification!

**Comment by Coresi7** [comment]
Thank you so much, I've learned a lot!
