### ISSUE TITLE
edit all RPU's when no "edits" specified in active area offset editor..

### ISSUE THREAD

**Issue by hyllm** [quietvoid/dovi_tool#40]
I have video, which has active area offset 276 top, 277 bottom, so i want to edit RPU to 0 top, 1 bottom, and encode with 276 top and 276 bottom crop... that way is should be pixel perfect. :)

the question is if it's possible to edit all frames by default, when no specifiyng edits... because right now i need to find number of RPU's first. :( it would be much simpler, if edits would be done to all frames by default. :)

**Comment by quietvoid** [comment]
Not currently.

**Comment by hyllm** [comment]
and do you have plans to implement it? :-)

**Comment by quietvoid** [comment]
Maybe.

**Comment by hyllm** [comment]
thanks!!!

**Comment by quietvoid** [comment]
Edits still have to be specified but this is now possible:
```json5
"edits": {
    "all": 0
}
```
