### ISSUE TITLE
add active area offsets

### ISSUE THREAD

**Issue by hyllm** [quietvoid/dovi_tool#41]
i have dovi metadata without active area offsets (no active area section at all) and I want to add ones... is this possible with editor? activearea.json (edited to my needs) does not add them..

**Comment by quietvoid** [comment]
Not possible right now.
I tried recently but it didn't work.

**Comment by quietvoid** [comment]
The default behavior should now be to add L5 metadata if it's not present.
Implemented in https://github.com/quietvoid/dovi_tool/commit/05c8d190ce66174d7fdcab16a4178aaffabfa1ed
