### ISSUE TITLE
active area offset...

### ISSUE THREAD

**Issue by hyllm** [quietvoid/dovi_tool#45]
Hi. :) Me again. :)

Is it possible to determine which frames have different activa area offsets? from-to? it would be useful when we have "IMAX" movies, where some scenes are 16:9 and some 2.35:1...

or would it be OK, to export to JSON, edit offsets in some editor and then convert back to RPU???

**Comment by quietvoid** [comment]
Reimporting from JSON is not supported and is not something I'm interested in adding.
You would have to script it yourself by reading the JSON.

Or edit the code directly, print the L5 metadata when parsing the RPU.

**Comment by hyllm** [comment]
find&replace function in editor would be great... :) ie.. find top offset 67 and replace by 0. find bottom 67 and replace by 0, find top 276 and replace by 210, find bottom 277 and replace by 211. (this is specifically for a movie i am trying to encode now)...

**Comment by quietvoid** [comment]
I don't see a simple structure for the edit config to add this.

**Comment by hyllm** [comment]
:( so the other and for now only option is to encode uncropped. :( i cannot find JSON viewer, which correctly works with 800MB JSON file...
