### ISSUE TITLE
Is it possible that Convert DV profile5(ICtCp) to BT.2020 HLG?

### ISSUE THREAD

**Issue by nilaoda** [quietvoid/dovi_tool#46]
Sample: [BT2111.U4K_DVp5.DolbyVision.zip](https://github.com/quietvoid/dovi_tool/files/7077920/BT2111.U4K_DVp5.DolbyVision.zip)

```
HDR Format                         : Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU
```

Wrong Color:

![image](https://user-images.githubusercontent.com/20772925/131367909-6251bb10-a155-494a-810a-cdca8daeae24.png)

Using dolby vision extension:

![image](https://user-images.githubusercontent.com/20772925/131367987-b5abfc24-3a67-4600-b1d1-20475491c882.png)

Is there a tool can do this convert?

**Comment by quietvoid** [comment]
No public tool, and it's out of scope for this project.

**Comment by nilaoda** [comment]
thanks

**Comment by ValZapod** [comment]
MPV can now do it perfectly with rehsaping and MMR.
