### ISSUE TITLE
transformers (2007) uhd bd can't extract dovi rpu

### ISSUE THREAD

**Issue by hyllm** [quietvoid/dovi_tool#5]
i can't extract metadata from transofrmers uhd bd (2007)

`thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src\dovi\rpu\vdr_rpu_data.rs:154:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by quietvoid** [comment]
Should be fixed in PR https://github.com/quietvoid/dovi_tool/pull/6
You can test binaries once they're built: https://github.com/quietvoid/dovi_tool/actions/runs/502730585

**Comment by hyllm** [comment]
so far tested on two transformers movies and works like a charm!!! thank you!!! if some problems will arise from the rest three movies, i'll write.

**Comment by hyllm** [comment]
all ok on all 5 transformers movies. :)
