### ISSUE TITLE
The P5 -> P8 conversion does not always work

### ISSUE THREAD

**Issue by djnice** [quietvoid/dovi_tool#51]
When I'm using the -j p5_to_p81.json parameter, the resulting RPU file is same as the source.
I'm upload the sample: [https://drive.google.com/file/d/1IiHhj0QOwo3kXCCd1P9VnEl7I43AjY5Y/view?usp=sharing](url)
Thanks for your work!

**Comment by quietvoid** [comment]
What version? What exact command line are you using?
It is working fine for me.

**Comment by djnice** [comment]
I'm tried 0.4.0 and 0.5.0 too.
The command line is:
`dovi_tool editor -i RPU.bin -j p5_to_p81.json --rpu-out RPU_81.bin`

**Comment by quietvoid** [comment]
What is in the JSON?
It should be
```json5
{
    "mode": 3
}
```

**Comment by djnice** [comment]
`{
    "p5_to_p81": true
}`

**Comment by quietvoid** [comment]
That's an old JSON, the option became mode 3.

**Comment by djnice** [comment]
Oh, thank you, it works!
