### ISSUE TITLE
Doubt about crop

### ISSUE THREAD

**Issue by manuelrn** [quietvoid/dovi_tool#55]
I have a question about crop.

The option `-c` / `--crop` what it does is find `Level5` and, if it is present, readjust the active area offsets to 0, correct?

I have noticed that if you crop an RPU without `Level5`, the edit does nothing, it remains intact.
However, if the RPU contains `Level5`, the edit does work and sets the active area offsets to 0.

My Doubt is:
With cropped videos, what is more recommended?
Is it better that the RPU has `Level5` with active area offsets at 0 or that `Level5` does not exist directly?
Or are they both exactly the same and is it indifferent?
<br/>

I ask since, for example, cropped WEB-DL RPUs usually come without `Level5`.  And when editing it and injecting it into another HEVC (UHD for example) `Level5` will still not exist even if the "crop" option is used.

However, if the RPU comes from UHD for example, it does contain `Level5` and when editing it and using the "crop" option, the active area offsets will be set to 0 instead of removing `Level5`.
<br/>

So, is one of the two options more recommended?
Or is the result identical in both cases?

And, in the second case, wouldn't the ideal be that cropping would always eliminate `Level5` in all cases?
So the RPU would be more optimized, with a smaller size.

Thanks and regards!

**Comment by quietvoid** [comment]
> Is it better that the RPU has Level5 with active area offsets at 0 or that Level5 does not exist directly?
Or are they both exactly the same and is it indifferent?

I don't know but I would assume there wouldn't be a difference.

> And, in the second case, wouldn't the ideal be that cropping would always eliminate Level5 in all cases?

There are cases of editing the RPU with `crop: true` and then specifying different aspect ratio scenes (with proper offsets).
Both `--crop` and the JSON editing use the same code, so I'd prefer leaving the `Level5` metadata with 0 instead of removing.

**Comment by manuelrn** [comment]
Okay, thanks for the reply @quietvoid.

If there is no problem in having the active area offsets at 0, instead of deleting them, then better that `Level5` is always present just in case.
<br/>

And in this case, do you consider updating the tool so that `Level5` is always generated?

I say this because when the "crop" option is used, if `Level5` is not present the RPU remains intact instead of adding `Level5` with the active area offsets set to 0. The "crop" option only works if `Level5` already exists previously.

However, if a "presets"/"edits" is specified with all active area offsets set to 0, in this case the RPU is edited to add a `Level5`.
But the RPU will not be edited if a "presets"/"edits" is not specified, when it should work the same way since the active area offsets of the "presets"/"edits" is 0 (default crop).

Thanks and regards!

**Comment by quietvoid** [comment]
Someone asked for a way to drop L5 metadata so I added it to the editor in 029a1ec8c69871d5a43e8d3b4bbc08e7d8525460
You can now either drop all of the L5 metadata blocks or only those with zero offsets.
