### ISSUE TITLE
Minor fix in README

### ISSUE THREAD

**Issue by manuelrn** [quietvoid/dovi_tool#56]
### Commands
* #### info
    Prints the parsed RPU data as JSON for a specific frame.  
    Frame indices start at 0.

    * Example to get metadata for frame 123: `dovi_tool info -i RPU.bin -f 124`  
<br/>
<br/>

This should look like this:
Example to get metadata for frame 124: `dovi_tool info -i RPU.bin -f 123`

Thanks and regards!

**Comment by quietvoid** [comment]
Fixed in https://github.com/quietvoid/dovi_tool/commit/83bf7ef6e0b716fbcad8856611b3e99d3a887e90
