### ISSUE TITLE
Question for profile conversion

### ISSUE THREAD

**Issue by madey83** [quietvoid/dovi_tool#64]
hi,

is it possible to:

1) convert DV profile 5 to DV profile 8.1
2) convert DV profile 5 to HDR10+ json file to be able to encode like HDR10+

**Comment by quietvoid** [comment]
> convert DV profile 5 to DV profile 8.1

Convert using mode 3.

> convert DV profile 5 to HDR10+ json file to be able to encode like HDR10+
No.

**Comment by madey83** [comment]
Hello,
Thank you for answer.

I did conversion DV profile 5 to DV profile 8.1 but when i re-encode video file originally encoded with DV profile 5 i got HDR info on my LG OLED TV but colors are not right. 
They looks like on example image below:

https://images.hdencode.com/upload/big/2021/08/18/611d5cecc93cb-hdencode_screenshot_1.png

**Comment by quietvoid** [comment]
Like I said profile 5 needs the video to be processed back into regular HDR10.

**Comment by madey83** [comment]
it means that i can't re-encode dolby vision profile 5 video (to reduce it size) into dolby vision/HDR10 profile 8.1 video.

**Comment by quietvoid** [comment]
Correct.

**Comment by madey83** [comment]
is it possible then re-encode video DV-5 to reduce it size to DV-5 ?
i tried but for some reason my file is not properly playable on my TV

**Comment by quietvoid** [comment]
It should be possible as long as the RPU is not modified.
