### ISSUE TITLE
How to merge RPU into MKV

### ISSUE THREAD

**Issue by netleader** [quietvoid/dovi_tool#7]
Hi,
I just found this tool a few days ago and it looks very promising.
I try to understand the workflow but I'm stuck at the point on how to merge the RPU back into an MKV file.
Could you give me a hint? 

Sorry if this doesn't belong here!

**Comment by quietvoid** [comment]
The only uses for the RPU is through x265, see their documentation: https://x265.readthedocs.io/en/3.1/cli.html#cmdoption-dolby-vision-rpu
