### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by theweasley** [quietvoid/dovi_tool#8]
Hey man. Tool has been working great so far. Was trying to do Transformers DV today and getting this new error which I've not seen before:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src/dovi/rpu/vdr_rpu_data.rs:154:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe
```

What do you think might be the problem?

**Comment by quietvoid** [comment]
What you posted is useless, it doesn't say anything.
Maybe have a look at https://github.com/quietvoid/dovi_tool/issues/5

**Comment by theweasley** [comment]
Alright, thank you. Wasn't sure how helpful that was but that was the error I had received and I've just copied it as-is. I am not on the latest public release so I'll give that a go as per the thread you referenced. Thanks!

**Comment by quietvoid** [comment]
You edited the message since I posted but that is exactly #5.
