### ISSUE TITLE
The 'main' thread panics when converting profile 5 to 8 with the latest version 1.3.1

### ISSUE THREAD

**Issue by manuelrn** [quietvoid/dovi_tool#80]
Hi!

With the latest version (1.3.1), I get this error when using mode 3 (converts profile 5 to 8):
`thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', dolby_vision\src\rpu\rpu_data_mapping.rs:236:46`

This does not happen with the previous version.

Thanks and regards!

**Comment by quietvoid** [comment]
Can you mention the source of the RPU?
It is erroring on `linear_interp_flag`, which was previously assumed to never be used.

**Comment by manuelrn** [comment]
I have tried several RPUs from different sources (Apple, Disney, Netflix, etc.), and I get that error with all of them.
And many of them come from very recent content (for example 'The Power of the Dog' from Netflix).

**Comment by quietvoid** [comment]
Thanks. Looking into it.

**Comment by quietvoid** [comment]
I've fixed it in 57d2cfd130128a8963081c086d7b1a86e8b7ff5a.

You can test binaries once they're ready: https://github.com/quietvoid/dovi_tool/actions/runs/1557214604
Will create a release tomorrow (for me!)

**Comment by quietvoid** [comment]
Fixed in 1.3.2.

**Comment by manuelrn** [comment]
Thanks @quietvoid!

I have tried the new version and now it works correctly again.
