### ISSUE TITLE
Thread hangs at "generating metadata" with Apple Silicon M1 chip using DoVi 4.0 XML

### ISSUE THREAD

**Issue by merlinmage** [quietvoid/dovi_tool#81]
Hello,

when using 1.3.0 stable, converting a DoVi 4.0 XML to a RPU bin file using --generate , the thread hans at "generate metadata" forever even when using a XML file with only one single shot. Using a 13" M1 MacBook Pro with Montery 12.0.1.

A DoVi 2.9 XML works fine though.

**Comment by quietvoid** [comment]
It seems to be broken because of the L3 metadata, and apparently I don't have an official sample for that.

**Comment by merlinmage** [comment]
> 

Here is a sample DoVi 4.0 XML:

https://pastebin.com/KxBYuBgW

**Comment by quietvoid** [comment]
Yeah I do have one, but level 3 metadata is not used in RPUs because it's CMv4 metadata.
And RPUs usually stick to only CMv2.9, which is why I don't have "real" samples.

**Comment by merlinmage** [comment]
Good to know, thanks for the heads up. :)

**Comment by quietvoid** [comment]
Should be fixed in 8f5bf223f540b653b4a0190d0352e422f3eba434.

**Comment by quietvoid** [comment]
It seems level 3 metadata is supposed to be in another structure of the RPU, which is currently not supported.
So the current behaviour may be incorrect.

**Comment by ValZapod** [comment]
> I don't have "real" samples.

Did you find v4 samples? Since I have LG C9 that supports v4, wanted to test what is so magical about it.

**Comment by quietvoid** [comment]
DM v2 is fully supported in `dovi_tool` 1.4.5.

**Comment by ValZapod** [comment]
> DM v2 is fully supported in `dovi_tool` 1.4.5.

I asked about CMv4.

**Comment by quietvoid** [comment]
Same thing. Look it up.
