### ISSUE TITLE
Implement that the 'info' command shows the total number of frames in case of 'out of range' error

### ISSUE THREAD

**Issue by manuelrn** [quietvoid/dovi_tool#88]
Hi!

When with the `info` command you try to see the information of a frame greater than the number of frames that the RPU contains, this error occurs:
```
Parsing RPU file...
Error: info: invalid frame number (out of range)
```
<br/>

Perhaps it would be useful for the user that, in addition to notifying this error, the number of available frames is also notified.
For example, something like this:
```
Parsing RPU file...
Error: info: invalid frame number (out of range)
Metadata length: 123456
```
<br/>

Thanks and regards!

**Comment by quietvoid** [comment]
Now prints something like this:
```
Parsing RPU file...
Error: info: invalid frame number (out of range).
Number of valid RPUs parsed: 185341
```

**Comment by manuelrn** [comment]
> Now prints something like this:
> 
> ```
> Parsing RPU file...
> Error: info: invalid frame number (out of range).
> Number of valid RPUs parsed: 185341
> ```

Thank you very much for your quick reply.
