### ISSUE TITLE
Mux profile 7 to iOS & MacOS compatible profile 5?

### ISSUE THREAD

**Issue by perrinpagess** [quietvoid/dovi_tool#92]
I want to mux a profile 7 BL+EL to a single stream profile 5 mp4 that's compatible with iOS and MacOS. Similar to what dolby has on their test stream database.

https://developer.dolby.com/tools-media/sample-media/video-streams/dolby-vision-streams/

Is this possible with dovi_tool?

**Comment by quietvoid** [comment]
No, it's not.

**Comment by perrinpagess** [comment]
Ok
